jobs:
  dependency-check:
    name: dependency-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build Maven with Docker Profile
      run: mvn clean install -Pdocker -DskipTests -B
    - continue-on-error: true
      env:
        JAVA_HOME: /opt/jdk
      id: dependency-check
      name: Dependency-Check Run
      uses: dependency-check/Dependency-Check_Action@main
      with:
        args: '--format JSON --prettyPrint

          '
        format: HTML
        path: .
        project: OWASP Security Shepherd
    - continue-on-error: true
      name: Publish Dependency-Check Results
      uses: actions/upload-artifact@master
      with:
        name: dependency_check_report
        path: ${{github.workspace}}/reports
name: Dependency-Check
on:
  repository_dispatch:
    types: trigger-ga___dependency-check.yml
