jobs:
  build:
    name: build
    needs: lint-java
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build Maven with Docker Profile
      run: mvn clean install -Pdocker -DskipTests -B
    - continue-on-error: true
      name: Docker Compose Build
      run: docker-compose build
  integration-tests:
    needs:
    - lint-java
    - build
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_DATABASE: core
          MYSQL_ROOT_PASSWORD: password
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
        ports:
        - 8888:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Start MYSQL Server
      run: sudo /etc/init.d/mysql start
    - continue-on-error: true
      name: Modify MySQL Connection Variables
      run: 'sed -i "s/''@''localhost''/''@''%''/g" ${GITHUB_WORKSPACE}/src/main/resources/database/moduleSchemas.sql

        sed -i ''s/TEST_MYSQL_PORT=3306/TEST_MYSQL_PORT=8888/g'' ${GITHUB_WORKSPACE}/.env

        '
    - continue-on-error: true
      name: Prepare Intergration Tests
      run: 'sudo apt-get -y install libargon2-0

        mvn -Pdocker validate

        '
    - continue-on-error: true
      name: Run Intergration Tests
      run: 'mvn verify -DskipUTs=true -DmongoDocker -B

        '
  lint-java:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: axel-op/googlejavaformat-action@fe78db8a90171b6a836449f8d0e982d5d71e5c5a
      with:
        args: --set-exit-if-changed
  unit-tests:
    needs:
    - lint-java
    - build
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_DATABASE: core
          MYSQL_ROOT_PASSWORD: password
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
        ports:
        - 8888:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Start MYSQL Server
      run: sudo /etc/init.d/mysql start
    - continue-on-error: true
      name: Modify MySQL Connection Variables
      run: 'sed -i "s/''@''localhost''/''@''%''/g" ${GITHUB_WORKSPACE}/src/main/resources/database/moduleSchemas.sql

        sed -i ''s/TEST_MYSQL_PORT=3306/TEST_MYSQL_PORT=8888/g'' ${GITHUB_WORKSPACE}/.env

        '
    - continue-on-error: true
      name: Run Unit Tests
      run: mvn test -B -e -X
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___test.yml
